name: Release

on:
  workflow_dispatch:
    inputs:
      bump:
        required: true
        type: choice
        options:
          - next
          - patch
          - minor
          - major
          - prepatch
          - preminor
          - premajor

      preid:
        type: choice
        required: true
        default: beta
        options:
          - alpha
          - beta
          - canary

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v4

      - run: pnpm i

      - run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - run: pnpm run packages:bump ${{ github.event.inputs.bump }} --yes --preid ${{ github.event.inputs.preid }}

      - id: package-version
        uses: martinbeentjes/npm-get-version-action@v1.3.1
        with:
          path: packages/server

      - id: prerelease-tag
        run: |
          VERSION=${{ steps.package-version.outputs.current-version }}

          if [[ $VERSION =~ ^[0-9\.]+(-([0-9A-Za-z-]+).*)?$ ]]; then
            echo "tag=${BASH_REMATCH[2]}"
          else
            echo "tag=unknown"
          fi

      - run: pnpm config set '//registry.npmjs.org/:_authToken' "${NPM_TOKEN}"
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - run: pnpm run packages:publish --tag="${{ steps.prerelease-tag.outputs.tag || 'latest' }}"
        env:
          NPM_CONFIG_PROVENANCE: true

      - run: pnpm run packages:changelog:github
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
